import { randomUUID } from "node:crypto";
import type { PrismaClient } from "../../generated/prisma/client.js";
import { deleteObject, getObjectBuffer, putObject } from "../../lib/r2.js";
import { prisma } from "../../utils/prisma.js";

export type GeneratedImageRecord = {
  id: string;
  userId: string;
  projectId: string | null;
  sessionId: string;
  r2Key: string;
  mediaType: string;
  width: number;
  height: number;
  modelId: string;
  prompt: string;
  nOfTotal: string | null;
  createdAt: Date;
};

/** Narrow prisma surface so tests can inject a fake (mirrors ApprovalRedis). */
export type ImageStorePrisma = Pick<
  PrismaClient,
  "generatedImage" | "chatSession" | "project" | "sessionImageContext"
>;

export type ImageStoreDeps = {
  prisma: ImageStorePrisma;
  putObject: (
    key: string,
    body: Uint8Array,
    contentType: string,
  ) => Promise<void>;
  getObjectBuffer: (key: string) => Promise<Uint8Array>;
  deleteObject: (key: string) => Promise<void>;
};

export function createImageStore(deps: ImageStoreDeps) {
  return {
    /** Upload the generated bytes to R2, then persist the metadata row. */
    async saveGeneratedImage(input: {
      userId: string;
      sessionId: string;
      projectId: string | null;
      buffer: Uint8Array;
      mediaType?: string;
      modelId: string;
      prompt: string;
      width: number;
      height: number;
      nOfTotal?: string;
    }): Promise<GeneratedImageRecord> {
      const mediaType = input.mediaType ?? "image/png";
      const r2Key = `images/${input.userId}/${randomUUID()}`;

      try {
        await deps.putObject(r2Key, Buffer.from(input.buffer), mediaType);

        return await deps.prisma.generatedImage.create({
          data: {
            userId: input.userId,
            sessionId: input.sessionId,
            projectId: input.projectId,
            r2Key,
            mediaType,
            width: input.width,
            height: input.height,
            modelId: input.modelId,
            prompt: input.prompt,
            ...(input.nOfTotal !== undefined
              ? { nOfTotal: input.nOfTotal }
              : {}),
          },
        });
      } catch (error) {
        // Avoid orphaned R2 objects when the row fails to persist. The
        // delete is best-effort (the upload may itself have failed).
        await deps.deleteObject(r2Key).catch(() => {});
        throw error;
      }
    },

    /**
     * Session gallery, gated on session ownership: a foreign session id
     * yields [] (no existence oracle).
     */
    async listSessionImages(input: {
      sessionId: string;
      userId: string;
    }): Promise<GeneratedImageRecord[]> {
      const session = await deps.prisma.chatSession.findFirst({
        where: { id: input.sessionId, userId: input.userId },
        select: { id: true },
      });
      if (!session) return [];

      return deps.prisma.generatedImage.findMany({
        where: { sessionId: input.sessionId },
        orderBy: { createdAt: "desc" },
      });
    },

    /**
     * Project gallery, gated on project ownership: a foreign project id
     * yields [] (no existence oracle).
     */
    async listProjectImages(input: {
      projectId: string;
      userId: string;
    }): Promise<GeneratedImageRecord[]> {
      const project = await deps.prisma.project.findFirst({
        where: { id: input.projectId, userId: input.userId },
      });
      if (!project) return [];

      return deps.prisma.generatedImage.findMany({
        where: { projectId: input.projectId },
        orderBy: { createdAt: "desc" },
      });
    },

    listUserImages(userId: string): Promise<GeneratedImageRecord[]> {
      return deps.prisma.generatedImage.findMany({
        where: { userId, projectId: null },
        orderBy: { createdAt: "desc" },
      });
    },

    getImage(id: string): Promise<GeneratedImageRecord | null> {
      return deps.prisma.generatedImage.findFirst({ where: { id } });
    },

    /** Fetch the stored image bytes for a row's r2Key. */
    getObjectBuffer: deps.getObjectBuffer,

    /**
     * Owner-or-project-member check for serving image bytes: the owner
     * passes, standalone images (no projectId) are owner-only, project
     * images additionally allow any chat-session member of the project.
     */
    async assertImageAccess(input: {
      userId: string;
      image: GeneratedImageRecord;
    }): Promise<boolean> {
      if (input.image.userId === input.userId) return true;
      if (input.image.projectId === null) return false;

      const membership = await deps.prisma.chatSession.findFirst({
        where: { projectId: input.image.projectId, userId: input.userId },
        select: { id: true },
      });
      return membership !== null;
    },

    /**
     * Active image context: images the user pinned as chat context for a
     * session. They are injected as image input into the agent prompt when
     * the selected model supports image input (see build-run-input).
     */
    async addSessionImageContext(input: {
      userId: string;
      sessionId: string;
      imageId: string;
    }): Promise<boolean> {
      const image = await deps.prisma.generatedImage.findFirst({
        where: { id: input.imageId },
        select: { id: true, userId: true, sessionId: true },
      });
      if (!image || image.userId !== input.userId) return false;
      if (image.sessionId !== input.sessionId) return false;

      await deps.prisma.sessionImageContext.upsert({
        where: {
          sessionId_imageId: {
            sessionId: input.sessionId,
            imageId: input.imageId,
          },
        },
        create: {
          userId: input.userId,
          sessionId: input.sessionId,
          imageId: input.imageId,
        },
        update: {},
      });
      return true;
    },

    async removeSessionImageContext(input: {
      userId: string;
      sessionId: string;
      imageId: string;
    }): Promise<void> {
      await deps.prisma.sessionImageContext.deleteMany({
        where: {
          userId: input.userId,
          sessionId: input.sessionId,
          imageId: input.imageId,
        },
      });
    },

    /**
     * Active image context is single-use: the run that consumes it clears it
     * so the next message starts clean (see run-worker).
     */
    async clearSessionImageContexts(input: {
      userId: string;
      sessionId: string;
    }): Promise<void> {
      await deps.prisma.sessionImageContext.deleteMany({
        where: {
          userId: input.userId,
          sessionId: input.sessionId,
        },
      });
    },

    async listSessionImageContexts(input: {
      userId: string;
      sessionId: string;
    }): Promise<GeneratedImageRecord[]> {
      const session = await deps.prisma.chatSession.findFirst({
        where: { id: input.sessionId, userId: input.userId },
        select: { id: true },
      });
      if (!session) return [];

      const rows = await deps.prisma.sessionImageContext.findMany({
        where: { sessionId: input.sessionId },
        orderBy: { createdAt: "asc" },
        include: { image: true },
      });
      return rows.map((row) => row.image);
    },
  };
}

export type ImageStore = ReturnType<typeof createImageStore>;

let imageStore: ImageStore | null = null;

/** Process-lifetime image store backed by the shared prisma + R2 clients. */
export function getImageStore(): ImageStore {
  if (!imageStore) {
    imageStore = createImageStore({
      prisma,
      putObject,
      getObjectBuffer,
      deleteObject,
    });
  }
  return imageStore;
}
