import { randomUUID } from "node:crypto";
import type { PrismaClient } from "../../generated/prisma/client.js";
import { getObjectBuffer, putObject } from "../../lib/r2.js";
import { prisma } from "../../utils/prisma.js";

export type GeneratedImageRecord = {
  id: string;
  userId: string;
  projectId: string | null;
  sessionId: string;
  r2Key: string;
  mediaType: string;
  width: number;
  height: number;
  modelId: string;
  prompt: string;
  nOfTotal: string | null;
  createdAt: Date;
};

/** Narrow prisma surface so tests can inject a fake (mirrors ApprovalRedis). */
export type ImageStorePrisma = Pick<
  PrismaClient,
  "generatedImage" | "chatSession"
>;

export type ImageStoreDeps = {
  prisma: ImageStorePrisma;
  putObject: (
    key: string,
    body: Uint8Array,
    contentType: string,
  ) => Promise<void>;
  getObjectBuffer: (key: string) => Promise<Uint8Array>;
};

export function createImageStore(deps: ImageStoreDeps) {
  return {
    /** Upload the generated bytes to R2, then persist the metadata row. */
    async saveGeneratedImage(input: {
      userId: string;
      sessionId: string;
      projectId: string | null;
      buffer: Uint8Array;
      mediaType?: string;
      modelId: string;
      prompt: string;
      width: number;
      height: number;
      nOfTotal?: string;
    }): Promise<GeneratedImageRecord> {
      const mediaType = input.mediaType ?? "image/png";
      const r2Key = `images/${input.userId}/${randomUUID()}`;

      await deps.putObject(r2Key, Buffer.from(input.buffer), mediaType);

      return deps.prisma.generatedImage.create({
        data: {
          userId: input.userId,
          sessionId: input.sessionId,
          projectId: input.projectId,
          r2Key,
          mediaType,
          width: input.width,
          height: input.height,
          modelId: input.modelId,
          prompt: input.prompt,
          ...(input.nOfTotal !== undefined
            ? { nOfTotal: input.nOfTotal }
            : {}),
        },
      });
    },

    listSessionImages(sessionId: string): Promise<GeneratedImageRecord[]> {
      return deps.prisma.generatedImage.findMany({
        where: { sessionId },
        orderBy: { createdAt: "desc" },
      });
    },

    listProjectImages(projectId: string): Promise<GeneratedImageRecord[]> {
      return deps.prisma.generatedImage.findMany({ where: { projectId } });
    },

    listUserImages(userId: string): Promise<GeneratedImageRecord[]> {
      return deps.prisma.generatedImage.findMany({
        where: { userId, projectId: null },
      });
    },

    getImage(id: string): Promise<GeneratedImageRecord | null> {
      return deps.prisma.generatedImage.findFirst({ where: { id } });
    },

    /** Fetch the stored image bytes for a row's r2Key. */
    getObjectBuffer: deps.getObjectBuffer,

    /**
     * Owner-or-project-member check for serving image bytes: the owner
     * passes, standalone images (no projectId) are owner-only, project
     * images additionally allow any chat-session member of the project.
     */
    async assertImageAccess(input: {
      userId: string;
      image: GeneratedImageRecord;
    }): Promise<boolean> {
      if (input.image.userId === input.userId) return true;
      if (input.image.projectId === null) return false;

      const membership = await deps.prisma.chatSession.findFirst({
        where: { projectId: input.image.projectId, userId: input.userId },
        select: { id: true },
      });
      return membership !== null;
    },
  };
}

export type ImageStore = ReturnType<typeof createImageStore>;

let imageStore: ImageStore | null = null;

/** Process-lifetime image store backed by the shared prisma + R2 clients. */
export function getImageStore(): ImageStore {
  if (!imageStore) {
    imageStore = createImageStore({ prisma, putObject, getObjectBuffer });
  }
  return imageStore;
}
