import type { Redis } from "ioredis";
import {
  CLIENT_STREAM_PROTOCOL,
  parseClientStreamEvent,
  type ClientDataMap,
  type ClientDataSchema,
  type ClientDataSchemas,
  type ClientMetadataSchema,
} from "@anvia/client";
import type {
  ClientResumableEvent,
  ResumableStreamCloseInput,
  ResumableStreamOpenInput,
  ResumableStreamRecord,
  ResumableStreamState,
  ResumableStreamStore,
  ResumableStreamStatus,
  ResumableStreamSubscribeInput,
} from "@anvia/server";
import { getRedis } from "./redis.js";

export type StreamMeta = {
  userId: string;
  sessionId: string;
  modelId: string;
  reasoningEffort: string | null;
};

// Keep every key for a stream in one Redis Cluster hash slot. The stream id
// is generated by the API, so it is safe to use as the hash-tag payload.
const STREAM_TAG = (streamId: string) => `{${streamId}}`;
const STATUS_KEY = (streamId: string) => `rs:${STREAM_TAG(streamId)}`;
const EVENTS_KEY = (streamId: string) => `rs:${STREAM_TAG(streamId)}:events`;
const COUNTER_KEY = (streamId: string) => `rs:${STREAM_TAG(streamId)}:counter`;
export const streamStopKey = (streamId: string) => `rs-stop:${STREAM_TAG(streamId)}`;

const OPEN_TTL_SECONDS = 6 * 60 * 60;
const CLOSE_TTL_SECONDS = 24 * 60 * 60;
const BLOCK_MS = 4000;
const END_MARKER = "__end__";

type RedisWithEval = Redis & {
  eval: (script: string, numKeys: number, ...args: string[]) => Promise<unknown>;
};

const OPEN_SCRIPT = `
local current = redis.call('HGET', KEYS[1], 'status')
if current then
  if current == 'running' then
    redis.call('EXPIRE', KEYS[1], ARGV[1])
    redis.call('EXPIRE', KEYS[2], ARGV[1])
    redis.call('EXPIRE', KEYS[3], ARGV[1])
  end
  return {0, current}
end
redis.call('HSET', KEYS[1], 'status', 'running')
redis.call('DEL', KEYS[2], KEYS[3])
redis.call('EXPIRE', KEYS[1], ARGV[1])
return {1, 'running'}
`;

const OPEN_META_SCRIPT = `
local current = redis.call('HGET', KEYS[1], 'status')
local function ownerMatches(field, value)
  local existing = redis.call('HGET', KEYS[1], field)
  return existing and existing == value
end
if not current then
  redis.call('HSET', KEYS[1], 'status', 'running', 'userId', ARGV[1], 'sessionId', ARGV[2], 'modelId', ARGV[3], 'reasoningEffort', ARGV[4])
  redis.call('DEL', KEYS[2], KEYS[3])
  redis.call('EXPIRE', KEYS[1], ARGV[5])
  return {1, 'running'}
end
if not ownerMatches('userId', ARGV[1]) or not ownerMatches('sessionId', ARGV[2]) or not ownerMatches('modelId', ARGV[3]) or not ownerMatches('reasoningEffort', ARGV[4]) then
  return {-1, 'owner-mismatch'}
end
if current == 'running' then
  redis.call('HSET', KEYS[1], 'userId', ARGV[1], 'sessionId', ARGV[2], 'modelId', ARGV[3], 'reasoningEffort', ARGV[4])
  redis.call('EXPIRE', KEYS[1], ARGV[5])
  redis.call('EXPIRE', KEYS[2], ARGV[5])
  redis.call('EXPIRE', KEYS[3], ARGV[5])
else
  redis.call('EXPIRE', KEYS[1], ARGV[6])
  redis.call('EXPIRE', KEYS[2], ARGV[6])
  redis.call('EXPIRE', KEYS[3], ARGV[6])
end
return {0, current}
`;

const APPEND_SCRIPT = `
local status = redis.call('HGET', KEYS[1], 'status')
if status ~= 'running' then return {0, status or ''} end
local eventId = redis.call('INCR', KEYS[3])
local entryId = tostring(eventId) .. '-0'
redis.call('XADD', KEYS[2], entryId, 'e', ARGV[1])
redis.call('EXPIRE', KEYS[1], ARGV[2])
redis.call('EXPIRE', KEYS[2], ARGV[2])
redis.call('EXPIRE', KEYS[3], ARGV[2])
return {eventId, entryId}
`;

const CLOSE_SCRIPT = `
local status = redis.call('HGET', KEYS[1], 'status')
if not status then return {0, 'missing', '0'} end
if status ~= 'running' then
  if status == ARGV[1] then
    redis.call('EXPIRE', KEYS[1], ARGV[2])
    redis.call('EXPIRE', KEYS[2], ARGV[2])
    redis.call('EXPIRE', KEYS[3], ARGV[2])
    return {0, status, redis.call('GET', KEYS[3]) or '0'}
  end
  return {-1, status, redis.call('GET', KEYS[3]) or '0'}
end
redis.call('HSET', KEYS[1], 'status', ARGV[1])
local visible = redis.call('GET', KEYS[3]) or '0'
local markerId = tostring(tonumber(visible) + 1) .. '-0'
redis.call('XADD', KEYS[2], markerId, 'e', cjson.encode({__end__=ARGV[1]}))
redis.call('EXPIRE', KEYS[1], ARGV[2])
redis.call('EXPIRE', KEYS[2], ARGV[2])
redis.call('EXPIRE', KEYS[3], ARGV[2])
return {1, ARGV[1], visible}
`;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function parseEventId(streamEntryId: string): number {
  const parsed = Number(streamEntryId.split("-", 1)[0]);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) {
    throw new Error(`Invalid Redis resumable stream entry id: ${streamEntryId}`);
  }
  return parsed;
}

function asNumber(value: unknown, label: string): number {
  const parsed = typeof value === "number" ? value : Number(value);
  if (!Number.isSafeInteger(parsed)) throw new Error(`Invalid Redis ${label}: ${String(value)}`);
  return parsed;
}

function isFinalStatus(value: unknown): value is "completed" | "error" {
  return value === "completed" || value === "error";
}

function isSentinel(value: unknown): value is { __end__: "completed" | "error" } {
  return isRecord(value) && Object.keys(value).length === 1 && isFinalStatus(value[END_MARKER]);
}

export type StoreValidationOptions = {
  metadataSchema?: ClientMetadataSchema;
  dataSchemas?: Record<string, ClientDataSchema>;
};

type SafeParseResult = { success: true; data: unknown } | { success: false; error: Error };

function schema(check: (value: unknown) => boolean): { safeParse(value: unknown): SafeParseResult } {
  return { safeParse(value) { return check(value) ? { success: true, data: value } : { success: false, error: new Error("Invalid protocol schema") }; } };
}

function exactKeys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): boolean {
  const allowed = new Set([...required, ...optional]);
  return required.every((key) => Object.prototype.hasOwnProperty.call(value, key)) && Object.keys(value).every((key) => allowed.has(key));
}

function boundedText(value: unknown, max: number): value is string {
  return typeof value === "string" && value.length > 0 && value.length <= max;
}

function boundedInteger(value: unknown, max: number): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0 && value <= max;
}

function validDefaultMetadata(value: unknown): boolean {
  if (!isRecord(value) || !exactKeys(value, ["sessionId", "modelId", "reasoningEffort"])) return false;
  return boundedText(value.sessionId, 200) && boundedText(value.modelId, 200) && (value.reasoningEffort === null || (typeof value.reasoningEffort === "string" && value.reasoningEffort.length <= 40));
}

function validDefaultData(name: string, value: unknown): boolean {
  if (!isRecord(value)) return false;
  if (name === "deepResearchProgress") {
    if (!exactKeys(value, ["phase", "message"], ["activities", "stats"]) || !["planning", "researching", "synthesizing", "completed", "failed"].includes(String(value.phase)) || !boundedText(value.message, 4000)) return false;
    if (value.activities !== undefined) {
      if (!Array.isArray(value.activities) || value.activities.length > 50 || !value.activities.every((activity) => isRecord(activity) && exactKeys(activity, ["id", "kind", "label", "status"]) && boundedText(activity.id, 200) && boundedText(activity.label, 240) && ["planning", "retrieval", "analysis", "verification", "synthesis"].includes(String(activity.kind)) && ["active", "done", "failed"].includes(String(activity.status)))) return false;
    }
    if (value.stats !== undefined) {
      if (!isRecord(value.stats) || !exactKeys(value.stats, ["retrievalCalls", "retrievalLimit"]) || !boundedInteger(value.stats.retrievalCalls, 100_000) || !boundedInteger(value.stats.retrievalLimit, 100_000) || value.stats.retrievalCalls > value.stats.retrievalLimit) return false;
    }
    return true;
  }
  if (name === "queuedMessageApplied") return exactKeys(value, ["clientMessageId", "attachmentCount"]) && boundedText(value.clientMessageId, 200) && boundedInteger(value.attachmentCount, 100);
  if (name === "toolWaitProgress") {
    return exactKeys(value, ["toolCallId", "toolName", "phase", "elapsedMs", "waitCount"], ["stage"]) &&
      boundedText(value.toolCallId, 200) &&
      boundedText(value.toolName, 200) &&
      ["running", "wait_elapsed", "awaiting", "cancelled", "completed", "failed"].includes(String(value.phase)) &&
      boundedInteger(value.elapsedMs, 86_400_000) &&
      boundedInteger(value.waitCount, 10_000) &&
      (value.stage === undefined || boundedText(value.stage, 240));
  }
  return false;
}

const DEFAULT_METADATA_SCHEMA = schema(validDefaultMetadata) as ClientMetadataSchema;
const DEFAULT_DATA_SCHEMAS = {
  deepResearchProgress: schema((value) => validDefaultData("deepResearchProgress", value)),
  queuedMessageApplied: schema((value) => validDefaultData("queuedMessageApplied", value)),
  toolWaitProgress: schema((value) => validDefaultData("toolWaitProgress", value)),
} as Record<string, ClientDataSchema>;

function parseStoredEvent(value: unknown, validation: StoreValidationOptions): ClientResumableEvent {
  if (!isRecord(value) || Object.keys(value).length !== 2) {
    throw new Error("Invalid resumable event envelope");
  }
  if (value.protocol !== CLIENT_STREAM_PROTOCOL || !isRecord(value.event)) {
    throw new Error("Unsupported resumable event protocol");
  }
  const event = parseClientStreamEvent(value.event, {
    metadataSchema: validation.metadataSchema ?? DEFAULT_METADATA_SCHEMA,
    dataSchemas: (validation.dataSchemas ?? DEFAULT_DATA_SCHEMAS) as ClientDataSchemas<ClientDataMap>,
  });
  return { protocol: CLIENT_STREAM_PROTOCOL, event };
}

function redisEval(redis: Redis, script: string, keys: string[], args: string[]): Promise<unknown> {
  const command = redis as unknown as Partial<RedisWithEval>;
  if (typeof command.eval !== "function") {
    throw new Error("Redis resumable stream store requires Redis EVAL support");
  }
  return command.eval(script, keys.length, ...keys, ...args);
}

function normalizeScriptResult(value: unknown): unknown[] {
  if (!Array.isArray(value)) throw new Error("Invalid Redis resumable stream script result");
  return value;
}

export function createRedisResumableStreamStore<TEvent = ClientResumableEvent>(
  redis: Redis,
  validation: StoreValidationOptions = {},
): ResumableStreamStore<TEvent> & {
  openWithMeta(input: ResumableStreamOpenInput, meta: StreamMeta): Promise<ResumableStreamState>;
  getMeta(streamId: string): Promise<StreamMeta | null>;
  setStopFlag(streamId: string): Promise<void>;
  hasStopFlag(streamId: string): Promise<boolean>;
  clearStopFlag(streamId: string): Promise<void>;
} {
  const stateFromHash = async (streamId: string): Promise<ResumableStreamState> => {
    const status = await redis.hget(STATUS_KEY(streamId), "status");
    if (status === null) return { status: "missing", lastEventId: 0 };
    if (status !== "running" && status !== "completed" && status !== "error") {
      throw new Error(`Invalid resumable stream status: ${status}`);
    }
    const counter = await redis.get(COUNTER_KEY(streamId));
    const lastEventId = Number(counter ?? 0);
    if (!Number.isSafeInteger(lastEventId) || lastEventId < 0) {
      throw new Error(`Invalid resumable stream event counter: ${String(counter)}`);
    }
    return { status: status as ResumableStreamStatus, lastEventId };
  };

  const store: ResumableStreamStore<TEvent> = {
    async open(input: ResumableStreamOpenInput): Promise<ResumableStreamState> {
      const result = normalizeScriptResult(await redisEval(
        redis,
        OPEN_SCRIPT,
        [STATUS_KEY(input.streamId), EVENTS_KEY(input.streamId), COUNTER_KEY(input.streamId)],
        [String(OPEN_TTL_SECONDS)],
      ));
      const created = asNumber(result[0], "open result");
      if (created < 0) throw new Error(`Resumable stream "${input.streamId}" open failed`);
      return stateFromHash(input.streamId);
    },

    async append(input: { streamId: string; event: TEvent }): Promise<ResumableStreamRecord<TEvent>> {
      let envelope: ClientResumableEvent;
      try {
        const serialized = JSON.stringify(input.event);
        if (serialized === undefined) throw new Error("Event is not JSON serializable");
        envelope = parseStoredEvent(input.event, validation);
        envelope = parseStoredEvent(JSON.parse(serialized), validation);
      } catch (error) {
        throw new Error("Invalid protocol-v3 resumable event", { cause: error });
      }
      const serialized = JSON.stringify(envelope);
      const result = normalizeScriptResult(await redisEval(
        redis,
        APPEND_SCRIPT,
        [STATUS_KEY(input.streamId), EVENTS_KEY(input.streamId), COUNTER_KEY(input.streamId)],
        [serialized, String(OPEN_TTL_SECONDS)],
      ));
      const eventId = asNumber(result[0], "append result");
      if (eventId === 0) {
        throw new Error(`Resumable stream "${input.streamId}" is not running (${String(result[1]) || "missing"})`);
      }
      return { streamId: input.streamId, eventId, event: envelope as unknown as TEvent, createdAt: new Date() };
    },

    subscribe(input: ResumableStreamSubscribeInput): AsyncIterable<ResumableStreamRecord<TEvent>> {
      const after = input.after ?? 0;
      if (!Number.isSafeInteger(after) || after < 0) {
        throw new Error(`Invalid resumable stream cursor: ${String(input.after)}`);
      }
      return {
        [Symbol.asyncIterator](): AsyncIterator<ResumableStreamRecord<TEvent>> {
          let lastRead = after;
          let finished = false;
          return {
            async next(): Promise<IteratorResult<ResumableStreamRecord<TEvent>>> {
              while (!finished) {
                const rows = await redis.xrange(
                  EVENTS_KEY(input.streamId),
                  `(${lastRead}-0`,
                  "+",
                  "COUNT",
                  128,
                );
                for (const row of rows as Array<[string, string[]]>) {
                  const [entryId, fields] = row;
                  const eventId = parseEventId(entryId);
                  if (eventId <= lastRead) continue;
                  if (!Array.isArray(fields) || fields.length < 2 || fields[0] !== "e") {
                    throw new Error("Malformed resumable stream Redis row");
                  }
                  let value: unknown;
                  try {
                    value = JSON.parse(fields[1]);
                  } catch (error) {
                    throw new Error("Malformed resumable stream JSON row", { cause: error });
                  }
                  if (isSentinel(value)) {
                    finished = true;
                    return { value: undefined, done: true };
                  }
                  const event = parseStoredEvent(value, validation) as TEvent;
                  if (eventId !== lastRead + 1) {
                    throw new Error(`Resumable stream event gap: expected ${lastRead + 1}, got ${eventId}`);
                  }
                  lastRead = eventId;
                  return {
                    value: { streamId: input.streamId, eventId, event, createdAt: new Date() },
                    done: false,
                  };
                }
                const state = await stateFromHash(input.streamId);
                if (state.status !== "running") {
                  finished = true;
                  return { value: undefined, done: true };
                }
                await redis.xread(
                  "COUNT",
                  64,
                  "BLOCK",
                  BLOCK_MS,
                  "STREAMS",
                  EVENTS_KEY(input.streamId),
                  `${lastRead}-0`,
                );
              }
              return { value: undefined, done: true };
            },
          };
        },
      };
    },

    async status(input: { streamId: string }): Promise<ResumableStreamState> {
      return stateFromHash(input.streamId);
    },

    async close(input: ResumableStreamCloseInput): Promise<ResumableStreamState> {
      const result = normalizeScriptResult(await redisEval(
        redis,
        CLOSE_SCRIPT,
        [STATUS_KEY(input.streamId), EVENTS_KEY(input.streamId), COUNTER_KEY(input.streamId)],
        [input.status, String(CLOSE_TTL_SECONDS)],
      ));
      const transition = asNumber(result[0], "close result");
      const observed = result[1];
      if (transition < 0 || (transition === 0 && observed !== "missing" && observed !== input.status)) {
        throw new Error(`Resumable stream "${input.streamId}" is already ${String(observed)}`);
      }
      return stateFromHash(input.streamId);
    },
  };

  return {
    ...store,
    async openWithMeta(input: ResumableStreamOpenInput, meta: StreamMeta): Promise<ResumableStreamState> {
      const result = normalizeScriptResult(await redisEval(
        redis,
        OPEN_META_SCRIPT,
        [STATUS_KEY(input.streamId), EVENTS_KEY(input.streamId), COUNTER_KEY(input.streamId)],
        [meta.userId, meta.sessionId, meta.modelId, meta.reasoningEffort ?? "", String(OPEN_TTL_SECONDS), String(CLOSE_TTL_SECONDS)],
      ));
      if (asNumber(result[0], "open metadata result") < 0) throw new Error(`Resumable stream "${input.streamId}" owner mismatch`);
      return stateFromHash(input.streamId);
    },
    async getMeta(streamId: string): Promise<StreamMeta | null> {
      const hash = await redis.hgetall(STATUS_KEY(streamId));
      if (!hash.status) return null;
      return {
        userId: hash.userId ?? "",
        sessionId: hash.sessionId ?? "",
        modelId: hash.modelId ?? "",
        reasoningEffort: hash.reasoningEffort || null,
      };
    },
    async setStopFlag(streamId: string): Promise<void> {
      await redis.set(streamStopKey(streamId), "1", "EX", 600);
    },
    async hasStopFlag(streamId: string): Promise<boolean> {
      return (await redis.exists(streamStopKey(streamId))) > 0;
    },
    async clearStopFlag(streamId: string): Promise<void> {
      await redis.del(streamStopKey(streamId));
    },
  };
}

export type ResumableStreamStoreWithMeta = ReturnType<typeof createRedisResumableStreamStore>;

let streamStore: ResumableStreamStoreWithMeta | null = null;

/** Process-wide singleton store; shared by the chat router and run worker. */
export function getStreamStore(): ResumableStreamStoreWithMeta {
  if (!streamStore) streamStore = createRedisResumableStreamStore(getRedis());
  return streamStore;
}
